title: Clínica Fabrício Afonso
description: >
Clínica de alergia e imunologia - Atendimentos médicos, exames e procedimentos terapêuticos, promovendo saúde e bem estar para toda família  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clinicafabricioafonso.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

paginate: 10
paginate_path: /blog/:num/

exclude:
  - gulpfile.js
  - pagegen.yml

sass:
  style: compressed

gems:
  - jekyll-coffeescript
  - jekyll-paginate

collections:
  sections:
    output: false
  categorias:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: blog/:title/
  - scope:
      path: ""
      type: categorias
    values:
      layout: categoria
      permalink: blog/:title.html

